import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

const API_KEY_STORAGE_KEY = 'gemini-api-key';

// This function will be the single source for getting an initialized client.
const getGeminiClient = () => {
    const apiKey = localStorage.getItem(API_KEY_STORAGE_KEY);
    if (!apiKey) {
        throw new Error("API 金鑰未設定。請在第一步中輸入您的 API 金鑰。");
    }
    return new GoogleGenAI({ apiKey });
};


const getBase64Parts = (base64Data: string) => {
  const match = base64Data.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid base64 string');
  }
  return { mimeType: match[1], data: match[2] };
};

const extractImageFromResponse = (response: GenerateContentResponse): string => {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error('No image was generated by the API.');
}

export const cleanImage = async (base64Image: string): Promise<string> => {
  const ai = getGeminiClient();
  const { mimeType, data } = getBase64Parts(base64Image);
  const prompt = `Your task is to be a hyper-realistic digital staging expert. Your goal is to completely empty the room in this photo, leaving only its fundamental architectural structure. You must remove **everything** that is not part of the building itself. This includes:
- All furniture (sofas, chairs, tables, beds, cabinets, etc.).
- All appliances, whether freestanding or built-in (TVs, refrigerators, lamps, speakers).
- All decorations and personal items (rugs, plants, books, photos).
- **Crucially, remove all objects attached to the walls, ceiling, or floor.** This includes wall art, clocks, mirrors, wall-mounted shelves, light fixtures, sconces, curtains and their rods.
The final image must be a photorealistic depiction of a completely vacant room, showing only the floor, walls, ceiling, windows, and doors. Seamlessly reconstruct the underlying surfaces, perfectly matching the original lighting, shadows, and textures. The room should look as if it has been completely cleared out for a new occupant.`;
  
  const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image-preview',
      contents: {
          parts: [
              { inlineData: { data, mimeType } },
              { text: prompt },
          ],
      },
      config: {
          responseModalities: [Modality.IMAGE, Modality.TEXT],
      },
  });

  return extractImageFromResponse(response);
};

export const furnishImage = async (base64Image: string, itemsPrompt: string): Promise<string> => {
  const ai = getGeminiClient();
  const { mimeType, data } = getBase64Parts(base64Image);
  const fullPrompt = `Using this image of an empty room as a base, add the following items according to the descriptions:\n${itemsPrompt}\n\nDo not add any other items. Generate a photorealistic image of the furnished room. The lighting and shadows of the new items should match the room's existing lighting.`;
  
  const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image-preview',
      contents: {
          parts: [
              { inlineData: { data, mimeType } },
              { text: fullPrompt },
          ],
      },
      config: {
          responseModalities: [Modality.IMAGE, Modality.TEXT],
      },
  });

  return extractImageFromResponse(response);
};